### ISSUE TITLE
Shaggytale

### ISSUE THREAD

**Issue by JJacobwow** [ics2oa-18-19/ics2oa-cpt-jacob-nathan-joseph#1]
Shaggy has become stronger than anything known to us.
S̡oḿe͡one͝ ͟he͟a̕r̷ o͠u̡r ca̕ll̨ f̀o̕r̴ h҉elp
P̡͍̟̻̘̹̪̯̞̺̣͉̰͓̱̜̮̦͡ļ̴͈̭̻͖̬͈͙͕̬̮͇̻̦̩̞̮͘͝e̴̢͖͓̺͍̮̻̝̜̮̩͙͍̥̞̹͓̯̰͎͘á̯̣̮̗͇͝ͅs̴̺͉̲͎̥̱̞̠̥͎̬̱̞̥̤̖̯͡ͅe̵̸̢̛͍̺̟͚̖͉̕
-

**Comment by MrGallo** [comment]
What is this?
